#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectUTS.Resource", IsApplication=true)]

namespace ConnectUTS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int darkBlue = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int lightBlue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
<<<<<<< HEAD
<<<<<<< HEAD
			public const int edit_text_style = 2130837504;
=======
			public const int gradient_background = 2130837504;
>>>>>>> origin/master
=======
			public const int gradient_background = 2130837504;
>>>>>>> origin/master
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int createAccountButton = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int password = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int passwordInput = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int rePassword = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int rePasswordInput = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int registerAccountButton = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int relativeLayout3 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int studentID = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int studentIDInput = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int testButton = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAccount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
