#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectUTS.Resource", IsApplication=true)]

namespace ConnectUTS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int black = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int buttonBlue = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int darkBlue = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int hint = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int lightBlue = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int white = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edit_text_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int createAccountButton = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int introHeading = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int likeUsTxt = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int loginButton = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int loginIDInput = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int loginIDText = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int loginPasswordInput = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int loginPasswordText = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int pwdRecoveryTxt = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int registerAccountButton = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int registerButton = 2131165188;
			
			// aapt resource value: 0x7f07000e
			public const int registerHeading = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int registerNationalityInput = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int registerPasswordInput = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int registerRePasswordInput = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int registerStudentIDInput = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int registerStudentNameInput = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int relativeLayout1 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int relativeLayout2 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int space1 = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int testButton = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RegisterScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int check_database = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int id_hint = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int like_on_facebook = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int log_in = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int password_hint = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int register = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int noTitle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
